/**
 * @file tuya_dp_defs.h
 * @brief Tuya IoT Data Point (DP) definitions — auto-generated from
 *        shared/protocols/tuya_dp_schema.json.
 *
 * This header is regenerated by tools/generate_dp_header.py. Do not edit
 * by hand — modify the JSON schema and re-run the generator.
 *
 * DP summary (schema v1.0.0):
 *   Upload  (device -> cloud): 10 DPs (IDs 1-10)
 *   Download (cloud -> device):  4 DPs (IDs 101-104)
 *   Total: 14 DPs
 *
 * @copyright Copyright (c) 2024 Railway Inspection AR Glasses Project
 * @license Apache-2.0
 *
 * @note Generated: 2024-01-01 — verify against tuya_dp_schema.json.
 */
#ifndef TUYA_DP_DEFS_H
#define TUYA_DP_DEFS_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* =========================================================================
 * DP Type enum (matches Tuya cloud type encoding)
 * ========================================================================= */

typedef enum {
    DP_TYPE_BOOL  = 0,  /**< Boolean (true/false)          */
    DP_TYPE_VALUE = 1,  /**< Numeric (int32 with min/max)  */
    DP_TYPE_STRING = 2,  /**< UTF-8 string                  */
    DP_TYPE_ENUM  = 3,  /**< Enumerated (index into range) */
    DP_TYPE_RAW   = 4,  /**< Raw binary (opaque bytes)     */
} dp_type_t;

/* =========================================================================
 * DP Direction enum
 * ========================================================================= */

typedef enum {
    DP_DIR_UPLOAD   = 0,  /**< Device -> Cloud (report)     */
    DP_DIR_DOWNLOAD = 1,  /**< Cloud -> Device (command)    */
} dp_direction_t;

/* =========================================================================
 * DP ID enum — Upload (device -> cloud), IDs 1-10
 * ========================================================================= */

typedef enum {
    /* --- Upload DPs (1-10) --- */
    DP_ID_DEVICE_ONLINE        = 1,   /**< bool, ro — 设备在线状态 */
    DP_ID_BATTERY_LEVEL        = 2,   /**< value [0-100]%, ro — 电池电量 */
    DP_ID_CHARGING_STATUS      = 3,   /**< bool, ro — 充电状态 */
    DP_ID_CAMERA_CONNECTED    = 4,   /**< bool, ro — 摄像头连接状态 */
    DP_ID_INSPECTION_TASK_ID   = 5,   /**< string(maxlen=64), ro — 当前巡检任务ID */
    DP_ID_DEVICE_MODE          = 6,   /**< enum, ro — 设备模式 */
    DP_ID_AI_DETECTION_SUMMARY = 7,   /**< string(maxlen=512), ro — AI检测摘要 */
    DP_ID_TELEMETRY            = 8,   /**< string(maxlen=256), ro — 设备遥测数据 */
    DP_ID_FIRMWARE_VERSION     = 9,   /**< string(maxlen=32), ro — 固件版本 */
    DP_ID_BLE_SIGNAL           = 10,  /**< value [-120..0]dBm, ro — BLE信号强度 */

    /* --- Download DPs (101-104) --- */
    DP_ID_REMOTE_REBOOT        = 101, /**< bool, rw — 远程重启 */
    DP_ID_MODE_SWITCH          = 102, /**< enum, rw — 模式切换 */
    DP_ID_BRIGHTNESS           = 103, /**< value [0-255], rw — 屏幕亮度 */
    DP_ID_VOLUME                = 104, /**< value [0-100]%, rw — 音量 */

    /** Sentinel: total number of DPs defined. */
    DP_ID_COUNT                = 14,
} dp_id_t;

/* =========================================================================
 * Device Mode enum values (for DP_ID_DEVICE_MODE / DP_ID_MODE_SWITCH)
 * ========================================================================= */

typedef enum {
    DP_MODE_STANDBY    = 0,  /**< standby  */
    DP_MODE_INSPECTING = 1,  /**< inspecting */
    DP_MODE_ALERT      = 2,  /**< alert */
    DP_MODE_CHARGING   = 3,  /**< charging */
    DP_MODE_OTA        = 4,  /**< ota */
} dp_mode_t;

/* =========================================================================
 * DP Code strings (for JSON serialisation and debugging)
 * ========================================================================= */

#define DP_CODE_DEVICE_ONLINE         "device_online"
#define DP_CODE_BATTERY_LEVEL         "battery_level"
#define DP_CODE_CHARGING_STATUS       "charging_status"
#define DP_CODE_CAMERA_CONNECTED      "camera_connected"
#define DP_CODE_INSPECTION_TASK_ID    "inspection_task_id"
#define DP_CODE_DEVICE_MODE           "device_mode"
#define DP_CODE_AI_DETECTION_SUMMARY  "ai_detection_summary"
#define DP_CODE_TELEMETRY             "telemetry"
#define DP_CODE_FIRMWARE_VERSION      "firmware_version"
#define DP_CODE_BLE_SIGNAL            "ble_signal"
#define DP_CODE_REMOTE_REBOOT         "remote_reboot"
#define DP_CODE_MODE_SWITCH           "mode_switch"
#define DP_CODE_BRIGHTNESS            "brightness"
#define DP_CODE_VOLUME                "volume"

/* =========================================================================
 * Property constraints (for value-type DPs)
 * ========================================================================= */

#define DP_BATTERY_MIN     0
#define DP_BATTERY_MAX     100
#define DP_BATTERY_STEP    1

#define DP_BRIGHTNESS_MIN  0
#define DP_BRIGHTNESS_MAX  255
#define DP_BRIGHTNESS_STEP 1

#define DP_VOLUME_MIN     0
#define DP_VOLUME_MAX     100
#define DP_VOLUME_STEP    1

#define DP_BLE_SIGNAL_MIN  (-120)
#define DP_BLE_SIGNAL_MAX  0
#define DP_BLE_SIGNAL_STEP 1

/* =========================================================================
 * String length limits
 * ========================================================================= */

#define DP_MAXLEN_INSPECTION_TASK_ID   64
#define DP_MAXLEN_AI_DETECTION_SUMMARY  512
#define DP_MAXLEN_TELEMETRY             256
#define DP_MAXLEN_FIRMWARE_VERSION      32

/* =========================================================================
 * Tuya DP command frame (on-wire format over BLE NUS)
 *
 * The Tuya BLE protocol wraps each DP in a Type-Length-Value frame:
 *   [dp_id:2B] [dp_type:1B] [len:2B] [value:lenB]
 *
 * The glasses firmware uses this struct to pack DP values into a
 * MSG_DEVICE_STATUS or MSG_DEVICE_CONFIG message payload.
 * ========================================================================= */

#define TUYA_DP_FRAME_HDR_SIZE  5U  /* id(2) + type(1) + len(2) */
#define TUYA_DP_MAX_VALUE_SIZE  512U  /* max string DP value */
#define TUYA_DP_MAX_FRAME_SIZE  (TUYA_DP_FRAME_HDR_SIZE + TUYA_DP_MAX_VALUE_SIZE)

/** Maximum total payload for a single DP report (multiple DPs batched). */
#define TUYA_DP_REPORT_MAX_PAYLOAD  1024U

/** Maximum number of DPs that can be batched in one report. */
#define TUYA_DP_REPORT_MAX_COUNT    14U

/**
 * @brief Tuya DP value union — covers all supported DP types.
 */
typedef struct {
    dp_type_t type;
    union {
        bool       bval;     /**< DP_TYPE_BOOL  */
        int32_t    ival;     /**< DP_TYPE_VALUE */
        const char *sval;    /**< DP_TYPE_STRING (points to external buffer) */
        uint32_t   eval;     /**< DP_TYPE_ENUM  */
        struct {
            const uint8_t *data;
            uint16_t       len;
        } raw;                /**< DP_TYPE_RAW   */
    } v;
} dp_value_t;

/**
 * @brief A single DP report entry (for batch upload).
 */
typedef struct {
    uint16_t   id;     /**< DP ID (see dp_id_t) */
    dp_type_t  type;   /**< DP type */
    uint16_t   len;     /**< Value length in bytes */
    const uint8_t *value; /**< Pointer to serialised value */
} dp_report_entry_t;

#ifdef __cplusplus
}
#endif

#endif /* TUYA_DP_DEFS_H */
